### ISSUE TITLE
Error on round start and the plugin does not work because of it

### ISSUE THREAD

**Issue by EsserGaming** [Marco15453/LightControl#1]
Version: 1.2.0

Here's the error:
`[2021-10-01 19:23:58.671 -05:00] [ERROR] [Exiled.Events] Method "OnRoundStarted" of the class "LightControl.EventHandler" caused an exception when handling the event "Exiled.Events.Events+CustomEventHandler"
[2021-10-01 19:23:58.683 -05:00] [ERROR] [Exiled.Events] System.NullReferenceException: Object reference not set to an instance of an object
  at Exiled.API.Features.Room.set_Color (UnityEngine.Color value) [0x00006] in <be8878af12b64e258471d95ac04ee163>:0 
  at LightControl.EventHandler.SetRoomColors () [0x000ba] in <70ff0094e54245508c9d790592da9ac6>:0 
  at LightControl.EventHandler.OnRoundStarted () [0x00000] in <70ff0094e54245508c9d790592da9ac6>:0 
  at Exiled.Events.Extensions.Event.InvokeSafely (Exiled.Events.Events+CustomEventHandler ev) [0x00024] in <ee2cf6f98d7f4abd9628f315d499b994>:0`

**Comment by Marco15453** [comment]
Can you provide your Config?

**Comment by EsserGaming** [comment]
```
light_control:
# Should the plugin be enabled?
  is_enabled: true
  # What Rooms should have what Color, See Room Example Config for the Format (If empty it will be ignored)
  rooms: []
  # What Zones should have what Color, See Zone Example Config for the Format (If empty it will be ignored)
  zones:
  - zone: Surface
    color:
      red: 252
      green: 132
      blue: 3
  - zone: HeavyContainment
    color:
      red: 252
      green: 132
      blue: 3
```
